# Generated by Django 5.2.6 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='open_graph_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='open_graph_image',
            field=models.FileField(blank=True, upload_to='open-graph/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='page',
            name='open_graph_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='service',
            name='open_graph_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='open_graph_image',
            field=models.FileField(blank=True, upload_to='open-graph/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='service',
            name='open_graph_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_open_graph_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_open_graph_image',
            field=models.FileField(blank=True, upload_to='open-graph/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_open_graph_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
